site_name: JavaScript CRD Tutorial

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - 'Introduction': 'index.md'
  - 'Creating data on local storage': 'creating.md'
  - 'Reading data on local storage': 'reading.md'
  - 'Deleting data on local storage': 'deleting.md'
  - 'Glossary': 'glossary.md'
  - 'Troubleshooting Guide': 'troubleshooting.md'

theme:
  features:
    - toc.follow
  icon:
    admonition:
      note: material/information
      warning: material/alert
      tip: material/star-box
  name: material
  palette:
    primary: light-green