site_name: JavaScript CRD Tutorial

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - 'Introduction': 'index.md'
  - 'Creating data on local storage': 'creating.md'
  - 'Reading data on local storage': 'reading.md'
  - 'Deleting data on local storage': 'deleting.md'
  - 'Glossary': 'glossary.md'
  - 'Troubleshooting Guide': 'troubleshooting.md'

theme:
  features:
    - toc.follow
  icon:
    admonition:
      note: material/information
      warning: material/alert
      tip: material/star-box
      failure: material/block-helper
  name: material
  palette:
    primary: light-green

    theme:
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: light-green
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light-green 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue-grey
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
